apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpme-auth-ms-postgres-deployment
  namespace: helpme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helpme-auth-ms-postgres
  template:
    metadata:
      labels:
        app: helpme-auth-ms-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: helpme-auth-db-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpme-auth-db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: helpme-auth-db-secrets
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-ms1-pvc