apiVersion: apps/v1
kind: Deployment
metadata:
  name: helpme-auth-ms-deployment
  namespace: helpme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helpme-auth-ms
  template:
    metadata:
      labels:
        app: helpme-auth-ms
    spec:
      containers:
      - name: helpme-auth-ms
        image: fischernz/helpme-auth-ms:1.0.5-SNAPSHOT
        ports:
        - containerPort: 8080
        env:
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: helpme-jwt-secrets
              key: JWT_SECRET
        - name: JWT_EXPIRATION_TIME_IN_MINUTES
          valueFrom:
            secretKeyRef:
              name: helpme-jwt-secrets
              key: JWT_EXPIRATION_TIME_IN_MINUTES

        - name: HOST
          valueFrom:
            secretKeyRef:
              name: helpme-auth-ms-secrets
              key: HOST
              
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: helpme-auth-db-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helpme-auth-db-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: helpme-auth-db-secrets
              key: POSTGRES_DB
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
