apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ms1-pv
  namespace: helpme
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres-ms1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-ms2-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres-ms2