apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ms1-pvc
  namespace: helpme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-ms2-pvc
  namespace: helpme
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi