apiVersion: v1
kind: Service
metadata:
  name: helpme-auth-ms-postgres-service
  namespace: helpme
spec:
  type: ClusterIP
  selector:
    app: helpme-auth-ms-postgres
  ports:
  - port: 5432
    targetPort: 5432
