apiVersion: v1
kind: Service
metadata:
  name: helpme-auth-ms-service
  namespace: helpme
  labels:
    app: helpme-auth-ms
spec:
  type: LoadBalancer
  selector:
    app: helpme-auth-ms
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
