apiVersion: v1
kind: Service
metadata:
  name: helpme-rabbitmq-service
  namespace: helpme
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672       # Exposing the RabbitMQ port
    targetPort: 5672
    name: amqp
  - port: 15672      # Exposing the RabbitMQ management UI port
    targetPort: 15672
    name: management
  type: ClusterIP     # Internal service (use LoadBalancer if exposing externally)
