apiVersion: v1
kind: Service
metadata:
  name: helpme-upload-ms-service
  namespace: helpme
  labels:
    app: helpme-upload-ms
spec:
  type: LoadBalancer
  selector:
    app: helpme-upload-ms
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
